name: django-rclone-storage

on:
  push:
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python: 3.7
            tox: flake8
          - python: 3.7
            tox: py37-django22
          - python: 3.8
            tox: py38-django22
          - python: 3.9
            tox: py39-django22
          - python: 3.7
            tox: py37-django30
          - python: 3.8
            tox: py38-django30
          - python: 3.9
            tox: py39-django30
          - python: 3.7
            tox: py37-django31
          - python: 3.8
            tox: py38-django31
          - python: 3.9
            tox: py39-django31
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox and any other packages
        run: pip install tox
      - name: Run Tox
        env:
          TOXENV: ${{ matrix.tox }}
        run: tox
