name: django-rclone-storage

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python: 3.5
            tox: flake8
          - python: 3.5
            tox: py35-django22
          - python: 3.6
            tox: py36-django22
          - python: 3.7
            tox: py37-django22
          - python: 3.8
            tox: py38-django22
          - python: 3.9
            tox: py39-django22
          - python: 3.6
            tox: py36-django30
          - python: 3.7
            tox: py37-django30
          - python: 3.8
            tox: py38-django30
          - python: 3.9
            tox: py39-django30
          - python: 3.6
            tox: py36-django31
          - python: 3.7
            tox: py37-django31
          - python: 3.8
            tox: py38-django31
          - python: 3.9
            tox: py39-django31
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
            python-version: ${{ matrix.python }}
      - name: Echo site details
        env:
            TOXENV: ${{ matrix.tox }}
      - name: Install Tox and any other packages
        run: pip install tox
      - name: Run Tox
        run: tox

  build-n-publish:
    needs: test
    name: Build and publish Python 🐍 distributions 📦 to PyPI and TestPyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/
      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
      - name: Publish distribution 📦 to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}